version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=codingblocks
      - RABBITMQ_DEFAULT_PASS=codingblocks
    ports:
      - "5672:5672"
      - "15672:15672"
  api:
    image: codingblocks/judge-api
    depends_on:
      - rabbitmq
    ports:
    - "3737:3737"
    env_file:
      - .env

  taskmaster:
    image: codingblocks/judge-taskmaster
    volumes:
      - "/tmp/runbox:/tmp/runbox"
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - rabbitmq
    env_file:
      - .env

  worker-c:
    image: codingblocks/judge-worker-c
  worker-java8:
    image: codingblocks/judge-worker-java8
  worker-cpp:
    image: codingblocks/judge-worker-cpp
  worker-py2:
    image: codingblocks/judge-worker-py2
